apiVersion: 1
datasources:
- name: Mimir
  type: prometheus
  access: proxy
  uid: mimir
  orgID: 1
  url: http://nginx:8080/prometheus
  isDefault: true
  jsonData:
    prometheusType: Mimir
- name: federation-frontend
  type: prometheus
  access: proxy
  uid: federation-frontend
  orgID: 1
  url: http://host.docker.internal:8089/prometheus
  jsonData:
    httpHeaderName1: X-Scope-OrgID
  secureJsonData:
    httpHeaderValue1: anonymous
