"services":
  "grafana-agent":
    "command":
      - "-config.file=/etc/agent-config/grafana-agent.yaml"
      - "-metrics.wal-directory=/tmp"
      - "-server.http.address=127.0.0.1:9091"
    "image": "grafana/agent:v0.37.3"
    "ports":
      - "9791:9091"
    "volumes":
      - "./config:/etc/agent-config"
  "memcached":
    "image": "memcached:1.6.19-alpine"
  "mimir-backend-1":
    "build":
      "context": "."
      "dockerfile": "dev.dockerfile"
    "command":
      - "./mimir"
      - "-config.file=./config/mimir.yaml"
      - "-target=backend"
      - "-activity-tracker.filepath=/activity/mimir-backend-1"
    "depends_on":
      - "minio"
    "environment": []
    "hostname": "mimir-backend-1"
    "image": "mimir"
    "ports":
      - "8706:8080"
    "volumes":
      - "./config:/mimir/config"
      - "./activity:/activity"
  "mimir-backend-2":
    "build":
      "context": "."
      "dockerfile": "dev.dockerfile"
    "command":
      - "./mimir"
      - "-config.file=./config/mimir.yaml"
      - "-target=backend"
      - "-activity-tracker.filepath=/activity/mimir-backend-2"
    "depends_on":
      - "minio"
    "environment": []
    "hostname": "mimir-backend-2"
    "image": "mimir"
    "ports":
      - "8707:8080"
    "volumes":
      - "./config:/mimir/config"
      - "./activity:/activity"
  "mimir-read-1":
    "build":
      "context": "."
      "dockerfile": "dev.dockerfile"
    "command":
      - "./mimir"
      - "-config.file=./config/mimir.yaml"
      - "-target=read"
      - "-activity-tracker.filepath=/activity/mimir-read-1"
    "depends_on":
      - "minio"
    "environment": []
    "hostname": "mimir-read-1"
    "image": "mimir"
    "ports":
      - "8704:8080"
    "volumes":
      - "./config:/mimir/config"
      - "./activity:/activity"
  "mimir-read-2":
    "build":
      "context": "."
      "dockerfile": "dev.dockerfile"
    "command":
      - "./mimir"
      - "-config.file=./config/mimir.yaml"
      - "-target=read"
      - "-activity-tracker.filepath=/activity/mimir-read-2"
    "depends_on":
      - "minio"
    "environment": []
    "hostname": "mimir-read-2"
    "image": "mimir"
    "ports":
      - "8705:8080"
    "volumes":
      - "./config:/mimir/config"
      - "./activity:/activity"
  "mimir-write-1":
    "build":
      "context": "."
      "dockerfile": "dev.dockerfile"
    "command":
      - "./mimir"
      - "-config.file=./config/mimir.yaml"
      - "-target=write"
      - "-activity-tracker.filepath=/activity/mimir-write-1"
    "depends_on":
      - "minio"
    "environment": []
    "hostname": "mimir-write-1"
    "image": "mimir"
    "ports":
      - "8701:8080"
    "volumes":
      - "./config:/mimir/config"
      - "./activity:/activity"
      - ".data-mimir-write-1:/data:delegated"
  "mimir-write-2":
    "build":
      "context": "."
      "dockerfile": "dev.dockerfile"
    "command":
      - "./mimir"
      - "-config.file=./config/mimir.yaml"
      - "-target=write"
      - "-activity-tracker.filepath=/activity/mimir-write-2"
    "depends_on":
      - "minio"
    "environment": []
    "hostname": "mimir-write-2"
    "image": "mimir"
    "ports":
      - "8702:8080"
    "volumes":
      - "./config:/mimir/config"
      - "./activity:/activity"
      - ".data-mimir-write-2:/data:delegated"
  "mimir-write-3":
    "build":
      "context": "."
      "dockerfile": "dev.dockerfile"
    "command":
      - "./mimir"
      - "-config.file=./config/mimir.yaml"
      - "-target=write"
      - "-activity-tracker.filepath=/activity/mimir-write-3"
    "depends_on":
      - "minio"
    "environment": []
    "hostname": "mimir-write-3"
    "image": "mimir"
    "ports":
      - "8703:8080"
    "volumes":
      - "./config:/mimir/config"
      - "./activity:/activity"
      - ".data-mimir-write-3:/data:delegated"
  "minio":
    "command":
      - "server"
      - "--console-address"
      - ":9701"
      - "/data"
    "environment":
      - "MINIO_ROOT_USER=mimir"
      - "MINIO_ROOT_PASSWORD=supersecret"
    "image": "minio/minio"
    "ports":
      - "9700:9700"
      - "9701:9701"
    "volumes":
      - ".data-minio:/data:delegated"
  "nginx":
    "environment":
      - "NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx"
      - "DISTRIBUTOR_HOST=mimir-write-1:8080"
      - "ALERT_MANAGER_HOST=mimir-backend-1:8080"
      - "RULER_HOST=mimir-backend-1:8080"
      - "QUERY_FRONTEND_HOST=mimir-read-1:8080"
      - "COMPACTOR_HOST=mimir-backend-1:8080"
    "hostname": "nginx"
    "image": "nginxinc/nginx-unprivileged:1.22-alpine"
    "ports":
      - "8780:8080"
    "volumes":
      - "../common/config:/etc/nginx/templates"
